server:
  port: 8083

spring:
  application:
    name: auth-service
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=5m
  datasource:
    url: ${AUTHDB_URL}
    username: ${AUTHDB_USERNAME}
    password: ${AUTHDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true